
title: Invoke-Obfuscation CLIP+ Launcher
ruletype: Sigma
author: Jonathan Cheong, oscd.community
date: 2020/10/13
description: Detects Obfuscated use of Clip.exe to execute PowerShell
detection:
  SELECTION_1:
    Provider_Name: Microsoft-Windows-Security-Auditing
  SELECTION_2:
    EventID: 4697
  SELECTION_3:
    ServiceFileName: '*cmd*'
  SELECTION_4:
    ServiceFileName: '*&&*'
  SELECTION_5:
    ServiceFileName: '*clipboard]::*'
  condition: (SELECTION_1 and SELECTION_2 and SELECTION_3 and SELECTION_4 and SELECTION_5)
falsepositives:
- Unknown
id: 4edf51e1-cb83-4e1a-bc39-800e396068e3
level: high
logsource:
  product: windows
  service: security
modified: 2022/02/24
references:
- https://github.com/Neo23x0/sigma/issues/1009
related:
- id: f7385ee2-0e0c-11eb-adc1-0242ac120002
  type: derived
status: experimental
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
